/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.imrenagi.analytics.events.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class project extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"project\",\"namespace\":\"com.imrenagi.analytics.events.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"name\",\"type\":[\"null\",\"string\"]},{\"name\":\"slug\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"cover\",\"type\":\"string\"},{\"name\":\"created_at\",\"type\":{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"org.apache.kafka.connect.data.Timestamp\"}},{\"name\":\"updated_at\",\"type\":{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"org.apache.kafka.connect.data.Timestamp\"}},{\"name\":\"deleted_at\",\"type\":[\"null\",{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"org.apache.kafka.connect.data.Timestamp\"}]},{\"name\":\"status\",\"type\":\"int\"},{\"name\":\"account_id\",\"type\":\"int\"},{\"name\":\"vendor_id\",\"type\":\"int\"},{\"name\":\"category_id\",\"type\":\"int\"},{\"name\":\"external_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"external_type\",\"type\":[\"null\",\"int\"]},{\"name\":\"location\",\"type\":\"string\"},{\"name\":\"cover_temp\",\"type\":\"string\"}],\"connect.name\":\"projects\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int id;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence slug;
  @Deprecated public java.lang.CharSequence description;
  @Deprecated public java.lang.CharSequence cover;
  @Deprecated public long created_at;
  @Deprecated public long updated_at;
  @Deprecated public java.lang.Long deleted_at;
  @Deprecated public int status;
  @Deprecated public int account_id;
  @Deprecated public int vendor_id;
  @Deprecated public int category_id;
  @Deprecated public java.lang.Long external_id;
  @Deprecated public java.lang.Integer external_type;
  @Deprecated public java.lang.CharSequence location;
  @Deprecated public java.lang.CharSequence cover_temp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public project() {}

  /**
   * All-args constructor.
   */
  public project(java.lang.Integer id, java.lang.CharSequence name, java.lang.CharSequence slug, java.lang.CharSequence description, java.lang.CharSequence cover, java.lang.Long created_at, java.lang.Long updated_at, java.lang.Long deleted_at, java.lang.Integer status, java.lang.Integer account_id, java.lang.Integer vendor_id, java.lang.Integer category_id, java.lang.Long external_id, java.lang.Integer external_type, java.lang.CharSequence location, java.lang.CharSequence cover_temp) {
    this.id = id;
    this.name = name;
    this.slug = slug;
    this.description = description;
    this.cover = cover;
    this.created_at = created_at;
    this.updated_at = updated_at;
    this.deleted_at = deleted_at;
    this.status = status;
    this.account_id = account_id;
    this.vendor_id = vendor_id;
    this.category_id = category_id;
    this.external_id = external_id;
    this.external_type = external_type;
    this.location = location;
    this.cover_temp = cover_temp;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return slug;
    case 3: return description;
    case 4: return cover;
    case 5: return created_at;
    case 6: return updated_at;
    case 7: return deleted_at;
    case 8: return status;
    case 9: return account_id;
    case 10: return vendor_id;
    case 11: return category_id;
    case 12: return external_id;
    case 13: return external_type;
    case 14: return location;
    case 15: return cover_temp;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: slug = (java.lang.CharSequence)value$; break;
    case 3: description = (java.lang.CharSequence)value$; break;
    case 4: cover = (java.lang.CharSequence)value$; break;
    case 5: created_at = (java.lang.Long)value$; break;
    case 6: updated_at = (java.lang.Long)value$; break;
    case 7: deleted_at = (java.lang.Long)value$; break;
    case 8: status = (java.lang.Integer)value$; break;
    case 9: account_id = (java.lang.Integer)value$; break;
    case 10: vendor_id = (java.lang.Integer)value$; break;
    case 11: category_id = (java.lang.Integer)value$; break;
    case 12: external_id = (java.lang.Long)value$; break;
    case 13: external_type = (java.lang.Integer)value$; break;
    case 14: location = (java.lang.CharSequence)value$; break;
    case 15: cover_temp = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'slug' field.
   */
  public java.lang.CharSequence getSlug() {
    return slug;
  }

  /**
   * Sets the value of the 'slug' field.
   * @param value the value to set.
   */
  public void setSlug(java.lang.CharSequence value) {
    this.slug = value;
  }

  /**
   * Gets the value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'cover' field.
   */
  public java.lang.CharSequence getCover() {
    return cover;
  }

  /**
   * Sets the value of the 'cover' field.
   * @param value the value to set.
   */
  public void setCover(java.lang.CharSequence value) {
    this.cover = value;
  }

  /**
   * Gets the value of the 'created_at' field.
   */
  public java.lang.Long getCreatedAt() {
    return created_at;
  }

  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.lang.Long value) {
    this.created_at = value;
  }

  /**
   * Gets the value of the 'updated_at' field.
   */
  public java.lang.Long getUpdatedAt() {
    return updated_at;
  }

  /**
   * Sets the value of the 'updated_at' field.
   * @param value the value to set.
   */
  public void setUpdatedAt(java.lang.Long value) {
    this.updated_at = value;
  }

  /**
   * Gets the value of the 'deleted_at' field.
   */
  public java.lang.Long getDeletedAt() {
    return deleted_at;
  }

  /**
   * Sets the value of the 'deleted_at' field.
   * @param value the value to set.
   */
  public void setDeletedAt(java.lang.Long value) {
    this.deleted_at = value;
  }

  /**
   * Gets the value of the 'status' field.
   */
  public java.lang.Integer getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.Integer value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'account_id' field.
   */
  public java.lang.Integer getAccountId() {
    return account_id;
  }

  /**
   * Sets the value of the 'account_id' field.
   * @param value the value to set.
   */
  public void setAccountId(java.lang.Integer value) {
    this.account_id = value;
  }

  /**
   * Gets the value of the 'vendor_id' field.
   */
  public java.lang.Integer getVendorId() {
    return vendor_id;
  }

  /**
   * Sets the value of the 'vendor_id' field.
   * @param value the value to set.
   */
  public void setVendorId(java.lang.Integer value) {
    this.vendor_id = value;
  }

  /**
   * Gets the value of the 'category_id' field.
   */
  public java.lang.Integer getCategoryId() {
    return category_id;
  }

  /**
   * Sets the value of the 'category_id' field.
   * @param value the value to set.
   */
  public void setCategoryId(java.lang.Integer value) {
    this.category_id = value;
  }

  /**
   * Gets the value of the 'external_id' field.
   */
  public java.lang.Long getExternalId() {
    return external_id;
  }

  /**
   * Sets the value of the 'external_id' field.
   * @param value the value to set.
   */
  public void setExternalId(java.lang.Long value) {
    this.external_id = value;
  }

  /**
   * Gets the value of the 'external_type' field.
   */
  public java.lang.Integer getExternalType() {
    return external_type;
  }

  /**
   * Sets the value of the 'external_type' field.
   * @param value the value to set.
   */
  public void setExternalType(java.lang.Integer value) {
    this.external_type = value;
  }

  /**
   * Gets the value of the 'location' field.
   */
  public java.lang.CharSequence getLocation() {
    return location;
  }

  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(java.lang.CharSequence value) {
    this.location = value;
  }

  /**
   * Gets the value of the 'cover_temp' field.
   */
  public java.lang.CharSequence getCoverTemp() {
    return cover_temp;
  }

  /**
   * Sets the value of the 'cover_temp' field.
   * @param value the value to set.
   */
  public void setCoverTemp(java.lang.CharSequence value) {
    this.cover_temp = value;
  }

  /** Creates a new project RecordBuilder */
  public static com.imrenagi.analytics.events.avro.project.Builder newBuilder() {
    return new com.imrenagi.analytics.events.avro.project.Builder();
  }
  
  /** Creates a new project RecordBuilder by copying an existing Builder */
  public static com.imrenagi.analytics.events.avro.project.Builder newBuilder(com.imrenagi.analytics.events.avro.project.Builder other) {
    return new com.imrenagi.analytics.events.avro.project.Builder(other);
  }
  
  /** Creates a new project RecordBuilder by copying an existing project instance */
  public static com.imrenagi.analytics.events.avro.project.Builder newBuilder(com.imrenagi.analytics.events.avro.project other) {
    return new com.imrenagi.analytics.events.avro.project.Builder(other);
  }
  
  /**
   * RecordBuilder for project instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<project>
    implements org.apache.avro.data.RecordBuilder<project> {

    private int id;
    private java.lang.CharSequence name;
    private java.lang.CharSequence slug;
    private java.lang.CharSequence description;
    private java.lang.CharSequence cover;
    private long created_at;
    private long updated_at;
    private java.lang.Long deleted_at;
    private int status;
    private int account_id;
    private int vendor_id;
    private int category_id;
    private java.lang.Long external_id;
    private java.lang.Integer external_type;
    private java.lang.CharSequence location;
    private java.lang.CharSequence cover_temp;

    /** Creates a new Builder */
    private Builder() {
      super(com.imrenagi.analytics.events.avro.project.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.imrenagi.analytics.events.avro.project.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.slug)) {
        this.slug = data().deepCopy(fields()[2].schema(), other.slug);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.description)) {
        this.description = data().deepCopy(fields()[3].schema(), other.description);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.cover)) {
        this.cover = data().deepCopy(fields()[4].schema(), other.cover);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.created_at)) {
        this.created_at = data().deepCopy(fields()[5].schema(), other.created_at);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.updated_at)) {
        this.updated_at = data().deepCopy(fields()[6].schema(), other.updated_at);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.deleted_at)) {
        this.deleted_at = data().deepCopy(fields()[7].schema(), other.deleted_at);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.status)) {
        this.status = data().deepCopy(fields()[8].schema(), other.status);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.account_id)) {
        this.account_id = data().deepCopy(fields()[9].schema(), other.account_id);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.vendor_id)) {
        this.vendor_id = data().deepCopy(fields()[10].schema(), other.vendor_id);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.category_id)) {
        this.category_id = data().deepCopy(fields()[11].schema(), other.category_id);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.external_id)) {
        this.external_id = data().deepCopy(fields()[12].schema(), other.external_id);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.external_type)) {
        this.external_type = data().deepCopy(fields()[13].schema(), other.external_type);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.location)) {
        this.location = data().deepCopy(fields()[14].schema(), other.location);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.cover_temp)) {
        this.cover_temp = data().deepCopy(fields()[15].schema(), other.cover_temp);
        fieldSetFlags()[15] = true;
      }
    }
    
    /** Creates a Builder by copying an existing project instance */
    private Builder(com.imrenagi.analytics.events.avro.project other) {
            super(com.imrenagi.analytics.events.avro.project.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.slug)) {
        this.slug = data().deepCopy(fields()[2].schema(), other.slug);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.description)) {
        this.description = data().deepCopy(fields()[3].schema(), other.description);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.cover)) {
        this.cover = data().deepCopy(fields()[4].schema(), other.cover);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.created_at)) {
        this.created_at = data().deepCopy(fields()[5].schema(), other.created_at);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.updated_at)) {
        this.updated_at = data().deepCopy(fields()[6].schema(), other.updated_at);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.deleted_at)) {
        this.deleted_at = data().deepCopy(fields()[7].schema(), other.deleted_at);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.status)) {
        this.status = data().deepCopy(fields()[8].schema(), other.status);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.account_id)) {
        this.account_id = data().deepCopy(fields()[9].schema(), other.account_id);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.vendor_id)) {
        this.vendor_id = data().deepCopy(fields()[10].schema(), other.vendor_id);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.category_id)) {
        this.category_id = data().deepCopy(fields()[11].schema(), other.category_id);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.external_id)) {
        this.external_id = data().deepCopy(fields()[12].schema(), other.external_id);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.external_type)) {
        this.external_type = data().deepCopy(fields()[13].schema(), other.external_type);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.location)) {
        this.location = data().deepCopy(fields()[14].schema(), other.location);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.cover_temp)) {
        this.cover_temp = data().deepCopy(fields()[15].schema(), other.cover_temp);
        fieldSetFlags()[15] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public com.imrenagi.analytics.events.avro.project.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public com.imrenagi.analytics.events.avro.project.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.imrenagi.analytics.events.avro.project.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'name' field */
    public com.imrenagi.analytics.events.avro.project.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'slug' field */
    public java.lang.CharSequence getSlug() {
      return slug;
    }
    
    /** Sets the value of the 'slug' field */
    public com.imrenagi.analytics.events.avro.project.Builder setSlug(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.slug = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'slug' field has been set */
    public boolean hasSlug() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'slug' field */
    public com.imrenagi.analytics.events.avro.project.Builder clearSlug() {
      slug = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'description' field */
    public java.lang.CharSequence getDescription() {
      return description;
    }
    
    /** Sets the value of the 'description' field */
    public com.imrenagi.analytics.events.avro.project.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.description = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'description' field has been set */
    public boolean hasDescription() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'description' field */
    public com.imrenagi.analytics.events.avro.project.Builder clearDescription() {
      description = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'cover' field */
    public java.lang.CharSequence getCover() {
      return cover;
    }
    
    /** Sets the value of the 'cover' field */
    public com.imrenagi.analytics.events.avro.project.Builder setCover(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.cover = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'cover' field has been set */
    public boolean hasCover() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'cover' field */
    public com.imrenagi.analytics.events.avro.project.Builder clearCover() {
      cover = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'created_at' field */
    public java.lang.Long getCreatedAt() {
      return created_at;
    }
    
    /** Sets the value of the 'created_at' field */
    public com.imrenagi.analytics.events.avro.project.Builder setCreatedAt(long value) {
      validate(fields()[5], value);
      this.created_at = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'created_at' field has been set */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'created_at' field */
    public com.imrenagi.analytics.events.avro.project.Builder clearCreatedAt() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'updated_at' field */
    public java.lang.Long getUpdatedAt() {
      return updated_at;
    }
    
    /** Sets the value of the 'updated_at' field */
    public com.imrenagi.analytics.events.avro.project.Builder setUpdatedAt(long value) {
      validate(fields()[6], value);
      this.updated_at = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'updated_at' field has been set */
    public boolean hasUpdatedAt() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'updated_at' field */
    public com.imrenagi.analytics.events.avro.project.Builder clearUpdatedAt() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'deleted_at' field */
    public java.lang.Long getDeletedAt() {
      return deleted_at;
    }
    
    /** Sets the value of the 'deleted_at' field */
    public com.imrenagi.analytics.events.avro.project.Builder setDeletedAt(java.lang.Long value) {
      validate(fields()[7], value);
      this.deleted_at = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'deleted_at' field has been set */
    public boolean hasDeletedAt() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'deleted_at' field */
    public com.imrenagi.analytics.events.avro.project.Builder clearDeletedAt() {
      deleted_at = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'status' field */
    public java.lang.Integer getStatus() {
      return status;
    }
    
    /** Sets the value of the 'status' field */
    public com.imrenagi.analytics.events.avro.project.Builder setStatus(int value) {
      validate(fields()[8], value);
      this.status = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'status' field has been set */
    public boolean hasStatus() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'status' field */
    public com.imrenagi.analytics.events.avro.project.Builder clearStatus() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'account_id' field */
    public java.lang.Integer getAccountId() {
      return account_id;
    }
    
    /** Sets the value of the 'account_id' field */
    public com.imrenagi.analytics.events.avro.project.Builder setAccountId(int value) {
      validate(fields()[9], value);
      this.account_id = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'account_id' field has been set */
    public boolean hasAccountId() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'account_id' field */
    public com.imrenagi.analytics.events.avro.project.Builder clearAccountId() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'vendor_id' field */
    public java.lang.Integer getVendorId() {
      return vendor_id;
    }
    
    /** Sets the value of the 'vendor_id' field */
    public com.imrenagi.analytics.events.avro.project.Builder setVendorId(int value) {
      validate(fields()[10], value);
      this.vendor_id = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'vendor_id' field has been set */
    public boolean hasVendorId() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'vendor_id' field */
    public com.imrenagi.analytics.events.avro.project.Builder clearVendorId() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'category_id' field */
    public java.lang.Integer getCategoryId() {
      return category_id;
    }
    
    /** Sets the value of the 'category_id' field */
    public com.imrenagi.analytics.events.avro.project.Builder setCategoryId(int value) {
      validate(fields()[11], value);
      this.category_id = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'category_id' field has been set */
    public boolean hasCategoryId() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'category_id' field */
    public com.imrenagi.analytics.events.avro.project.Builder clearCategoryId() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'external_id' field */
    public java.lang.Long getExternalId() {
      return external_id;
    }
    
    /** Sets the value of the 'external_id' field */
    public com.imrenagi.analytics.events.avro.project.Builder setExternalId(java.lang.Long value) {
      validate(fields()[12], value);
      this.external_id = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'external_id' field has been set */
    public boolean hasExternalId() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'external_id' field */
    public com.imrenagi.analytics.events.avro.project.Builder clearExternalId() {
      external_id = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'external_type' field */
    public java.lang.Integer getExternalType() {
      return external_type;
    }
    
    /** Sets the value of the 'external_type' field */
    public com.imrenagi.analytics.events.avro.project.Builder setExternalType(java.lang.Integer value) {
      validate(fields()[13], value);
      this.external_type = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'external_type' field has been set */
    public boolean hasExternalType() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'external_type' field */
    public com.imrenagi.analytics.events.avro.project.Builder clearExternalType() {
      external_type = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'location' field */
    public java.lang.CharSequence getLocation() {
      return location;
    }
    
    /** Sets the value of the 'location' field */
    public com.imrenagi.analytics.events.avro.project.Builder setLocation(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.location = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'location' field has been set */
    public boolean hasLocation() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'location' field */
    public com.imrenagi.analytics.events.avro.project.Builder clearLocation() {
      location = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'cover_temp' field */
    public java.lang.CharSequence getCoverTemp() {
      return cover_temp;
    }
    
    /** Sets the value of the 'cover_temp' field */
    public com.imrenagi.analytics.events.avro.project.Builder setCoverTemp(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.cover_temp = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'cover_temp' field has been set */
    public boolean hasCoverTemp() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'cover_temp' field */
    public com.imrenagi.analytics.events.avro.project.Builder clearCoverTemp() {
      cover_temp = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    @Override
    public project build() {
      try {
        project record = new project();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.slug = fieldSetFlags()[2] ? this.slug : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.description = fieldSetFlags()[3] ? this.description : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.cover = fieldSetFlags()[4] ? this.cover : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.created_at = fieldSetFlags()[5] ? this.created_at : (java.lang.Long) defaultValue(fields()[5]);
        record.updated_at = fieldSetFlags()[6] ? this.updated_at : (java.lang.Long) defaultValue(fields()[6]);
        record.deleted_at = fieldSetFlags()[7] ? this.deleted_at : (java.lang.Long) defaultValue(fields()[7]);
        record.status = fieldSetFlags()[8] ? this.status : (java.lang.Integer) defaultValue(fields()[8]);
        record.account_id = fieldSetFlags()[9] ? this.account_id : (java.lang.Integer) defaultValue(fields()[9]);
        record.vendor_id = fieldSetFlags()[10] ? this.vendor_id : (java.lang.Integer) defaultValue(fields()[10]);
        record.category_id = fieldSetFlags()[11] ? this.category_id : (java.lang.Integer) defaultValue(fields()[11]);
        record.external_id = fieldSetFlags()[12] ? this.external_id : (java.lang.Long) defaultValue(fields()[12]);
        record.external_type = fieldSetFlags()[13] ? this.external_type : (java.lang.Integer) defaultValue(fields()[13]);
        record.location = fieldSetFlags()[14] ? this.location : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.cover_temp = fieldSetFlags()[15] ? this.cover_temp : (java.lang.CharSequence) defaultValue(fields()[15]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
